import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { loadStudioModels } from './studio-models.mjs';

const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toolsMarkup = full => `<div class="viewer-tools" hidden><button type="button" data-viewer-action="left" aria-label="Look left">←</button><button type="button" data-viewer-action="right" aria-label="Look right">→</button>${full?'<button type="button" data-viewer-action="in" aria-label="Zoom in">+</button><button type="button" data-viewer-action="out" aria-label="Zoom out">−</button>':''}<button type="button" data-viewer-action="reset" aria-label="Reset room view">↺</button><button type="button" data-viewer-action="fullscreen" aria-label="Open room view fullscreen">⤢</button></div>`;
const tourUrl=(room,design,mode='walkthrough')=>`/studio.html?room=${room.id}&amp;mode=${mode}&amp;design=${design.id}`;
export async function renderStudio({root=process.cwd()}={}) {
  const input=JSON.parse(await readFile(join(root,'content/panoramas.json'),'utf8'));
  const models=await loadStudioModels(root,input.flatMap(room=>room.designs||[room])),modelMap=new Map(models.map(model=>[model.id,model]));
  const presentation=({id,title,src,preview,width,height,description,alt,kind,yaw,pitch})=>({id,title,src,preview,width,height,description,alt,kind,yaw,pitch});
  const rooms=input.map(room=>({...presentation(room),category:room.category,designs:(room.designs||[room]).map(design=>({...presentation(design),layoutId:design.id,highlights:modelMap.get(design.id).highlights}))}));
  const first=rooms.find(room=>room.width>=3840)||rooms[0],firstDesign=first.designs[0],totalDesigns=rooms.reduce((sum,room)=>sum+room.designs.length,0);
  const firstCaption=`${first.kind==='existing-visualisation'?'From the Alankaar visualisation collection.':'AI-generated design concept.'} 4K source image. Drag to look around, or take the guided tour.`;
  for(const room of rooms){
    if(!/^[a-z-]+$/.test(room.id))throw new Error('Invalid panorama category.');const ids=new Set();
    for(const design of room.designs){if(!/^[a-z0-9-]+$/.test(design.id)||ids.has(design.id)||!/^\/img\/panoramas\/[a-z0-9/-]+\.webp$/.test(design.src)||!/^\/img\/panoramas\/[a-z0-9/-]+\.webp$/.test(design.preview)||design.width!==design.height*2)throw new Error('Invalid panoramic design.');ids.add(design.id);}
  }
  await writeFile(join(root,'js/studio-rooms.json'),JSON.stringify(rooms)+'\n');
  await writeFile(join(root,'js/studio-layouts.json'),JSON.stringify(models)+'\n');
  const homePath=join(root,'index.html');let home=await readFile(homePath,'utf8');
  home=home.replaceAll('>360° studio</a>','>360° walkthroughs</a>');
  const featuredRooms=['living-rooms','shops','bathrooms','pooja'].map(id=>rooms.find(room=>room.id===id));
  const feature=`<section class="virtual-section section-space" id="virtual-studio"><div class="container">
<div class="section-heading"><div><p class="eyebrow light"><span class="orange-dash"></span> 360° walkthroughs · 4K designs</p><h2>See the room.<br><em>Then step inside.</em></h2></div><p>Look around in 4K, take a guided tour, or walk between viewpoints in a 3D version of the design you love.</p></div>
<div class="virtual-feature"><div class="virtual-preview" data-viewer data-room="${first.id}" data-mode="panorama"><img class="viewer-poster" src="${first.preview}" alt="${escape(first.alt)}" width="1200" height="600" loading="lazy"><div class="viewer-mount" tabindex="0" role="region" aria-label="Interactive 360 degree room view. Drag to look around or use the arrow keys."></div><span class="preview-corner">4K · 360° ROOM TOUR</span><button class="start-viewer" type="button"><span class="start-orbit" aria-hidden="true">360°<span>↔</span></span><strong>Look around in 4K</strong><small>Drag to explore the room</small></button><p class="viewer-status" role="status" aria-live="polite"></p>${toolsMarkup(false)}</div>
<div class="virtual-copy"><span class="studio-label">A walkthrough for every design</span><h3>More than a<br>single picture.</h3><p>Explore the finishes, see where the furniture sits and find a design that feels right for your space.</p><div class="studio-facts"><span><strong>${totalDesigns}</strong> designs with walkthroughs</span><span><strong>${rooms.length}</strong> kinds of spaces</span></div><a class="button button-primary" href="${tourUrl(first,firstDesign)}">Start a walkthrough <span aria-hidden="true">↗</span></a><a class="walkthrough-secondary" href="/studio.html#walkthrough-library">Browse all ${totalDesigns} walkthroughs →</a><p class="studio-disclosure">4K design concepts with matching 3D interpretations. Model proportions are approximate.</p></div></div>
<div class="walkthrough-picks" aria-label="Featured interior walkthroughs">${featuredRooms.map(room=>`<a href="${tourUrl(room,room.designs[0])}"><div><img src="${room.preview}" alt="${escape(room.alt)}" width="600" height="300" loading="lazy"><span class="walkthrough-play" aria-hidden="true">↗</span></div><span><strong>${escape(room.category)}</strong><small>${room.designs.length} designs · Start a walkthrough</small></span></a>`).join('')}</div>
<div class="studio-quicklinks" aria-label="Choose a 360 degree room">${rooms.map(room=>`<a href="/studio.html?room=${room.id}&amp;mode=walkthrough">${escape(room.category)} <span aria-hidden="true">↗</span></a>`).join('')}</div>
</div></section>`;
  const start='<!-- HOME_STUDIO_START -->',end='<!-- HOME_STUDIO_END -->';if(!home.includes(start)||!home.includes(end))throw new Error('Missing virtual studio markers.');
  home=home.slice(0,home.indexOf(start)+start.length)+'\n'+feature+'\n'+home.slice(home.indexOf(end));
  await writeFile(homePath,home);
  const header=home.match(/<header class="site-header"[\s\S]*?<\/header>/)[0].replaceAll('href="#','href="/#');
  const cards=rooms.map(room=>`<a class="studio-room-card" data-select-room="${room.id}" href="/studio.html?room=${room.id}"><div><img src="${room.preview}" alt="${escape(room.alt)}" width="600" height="300" loading="lazy"><span>${room.designs.length} walkthrough designs · 4K</span></div><h3>${escape(room.category)} <span aria-hidden="true">↗</span></h3><p>4K panorama · Walkthrough · Matching 3D layout</p></a>`).join('\n');
  const library=rooms.map(room=>`<div class="walkthrough-category"><h3>${escape(room.category)} <span>${room.designs.length} designs</span></h3><div class="walkthrough-library-grid">${room.designs.map(design=>`<article class="walkthrough-card" data-walkthrough-design="${design.id}"><a class="walkthrough-cover" data-open-tour href="${tourUrl(room,design)}"><img src="${design.preview}" alt="${escape(design.alt)}" width="600" height="300" loading="lazy"><span class="walkthrough-quality">4K + 3D</span><span class="walkthrough-play" aria-hidden="true">↗</span></a><div><h4><a data-open-tour href="${tourUrl(room,design)}">${escape(design.title)}</a></h4><p>Four viewpoints to explore</p><div class="walkthrough-card-links"><a data-open-tour href="${tourUrl(room,design)}">Start walkthrough ↗</a><a data-open-tour href="${tourUrl(room,design,'panorama')}&amp;tour=1">4K tour</a></div></div></article>`).join('')}</div></div>`).join('\n');
  const page=`<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#FF9800"><title>360° Interior Walkthroughs & 3D Designs | Alankaar Interiors</title><meta name="description" content="Explore 40 interior designs in 4K. Take a guided 360° tour, move through a matching 3D room and see its layout. Homes, shops, bathrooms and more."><link rel="canonical" href="https://alankaarinteriors.com/studio.html"><meta property="og:title" content="Explore 40 interior walkthroughs | Alankaar Interiors"><meta property="og:description" content="4K room tours, design-specific walkthroughs and matching 3D layouts for every part of your home or business."><meta property="og:type" content="website"><meta property="og:locale" content="en_IN"><meta name="twitter:card" content="summary_large_image"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:url" content="https://alankaarinteriors.com/studio.html"><meta property="og:image" content="https://alankaarinteriors.com${first.preview}"><link rel="icon" href="/img/logo/logo-A.png"><link rel="stylesheet" href="/css/site.css"><link rel="stylesheet" href="/css/studio.css"><script src="/js/site.js" defer></script><script type="module" src="/js/studio.js"></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'CollectionPage',name:'Alankaar 360° interior walkthroughs',url:'https://alankaarinteriors.com/studio.html',description:'Forty 4K interior design visualisations with guided panorama tours and corresponding approximate 3D room models.',isPartOf:{'@type':'WebSite',url:'https://alankaarinteriors.com/'}})}</script></head><body class="studio-page"><a class="skip-link" href="#main">Skip to content</a>${header}<main id="main">
<section class="studio-intro container"><a class="studio-back" href="/#virtual-studio">← Back to Alankaar</a><p class="eyebrow"><span class="orange-dash"></span> The virtual design studio</p><div class="studio-title-row"><h1>Explore in 360°.</h1><p>Choose a design. Take a look around.<br>See how the same room comes together.</p></div><a class="studio-tour-banner" href="#walkthrough-library"><span class="tour-banner-icon" aria-hidden="true">360°</span><span><strong>${totalDesigns} designs. A walkthrough for each.</strong><small>Guided 4K tours, room viewpoints and matching layouts.</small></span><span>Explore all walkthroughs ↗</span></a></section>
<section class="container studio-explorer" aria-label="Explore a room design"><div class="studio-toolbar"><label for="studio-room">Your space<select id="studio-room">${rooms.map(room=>`<option value="${room.id}">${escape(room.category)}</option>`).join('')}</select></label><div class="studio-modes" role="group" aria-label="Choose view type"><button type="button" data-view-mode="panorama" aria-pressed="true">4K panorama</button><button type="button" data-view-mode="walkthrough" aria-pressed="false">Walkthrough <span aria-hidden="true">↗</span></button><button type="button" data-view-mode="layout" aria-pressed="false">3D layout</button></div></div>
<div class="studio-design-picker" id="studio-design-picker" hidden><div class="design-picker-heading"><p>Choose a design</p><span id="studio-design-count"></span></div><div class="studio-design-strip" id="studio-design-strip" role="group" aria-label="Choose an interior design"></div></div>
<div class="studio-main-view virtual-preview" data-viewer data-room="${first.id}" data-mode="panorama"><img class="viewer-poster" src="${first.preview}" alt="${escape(first.alt)}" width="1200" height="600"><div class="viewer-mount" tabindex="0" role="region" aria-label="Interactive room view. Drag to rotate, use arrow keys, or use the view controls."></div><div class="walkthrough-pins" aria-label="Move to a room viewpoint"></div><button class="start-viewer" type="button"><span class="start-orbit" aria-hidden="true">360°<span>↔</span></span><strong>Explore this room</strong><small>Drag to look around</small></button><p class="viewer-status" role="status" aria-live="polite"></p>${toolsMarkup(true)}</div>
<div class="studio-tour-panel" id="studio-tour-panel" hidden><div class="tour-panel-main"><div class="tour-panel-heading"><div><span class="tour-kicker">Explore the details</span><h2 id="tour-title">Take a guided look</h2></div><div class="tour-playback"><button type="button" id="tour-previous" aria-label="Previous tour stop">←</button><button type="button" id="tour-play" aria-pressed="false">Play tour</button><button type="button" id="tour-next" aria-label="Next tour stop">→</button></div></div><div id="tour-stops" class="tour-stops" role="group" aria-label="Tour stops"></div><p id="tour-detail" class="tour-detail" role="status" aria-live="polite"></p></div><div id="tour-plan" class="tour-plan" role="group" aria-label="Room viewpoint map" hidden></div></div>
<div class="studio-view-caption"><div><h2 id="studio-view-title">${escape(first.title)}</h2><p id="studio-view-description">${escape(firstCaption)}</p></div><a class="text-link" href="/#contact">Plan a space like this <span aria-hidden="true">↗</span></a></div></section>
<section class="container studio-collection" aria-labelledby="room-collection-title"><div class="section-heading"><div><p class="eyebrow"><span class="orange-dash"></span> Find your space</p><h2 id="room-collection-title">Every room, ready to explore.</h2></div><p>Each design has its own 4K panorama, walkthrough and corresponding 3D layout.</p></div><div class="studio-room-grid">${cards}</div></section>
<section class="walkthrough-library section-space" id="walkthrough-library"><div class="container"><div class="section-heading"><div><p class="eyebrow"><span class="orange-dash"></span> The walkthrough collection</p><h2>Step into a design you love.</h2></div><p>${totalDesigns} designs across ${rooms.length} kinds of spaces. Start a walkthrough, or explore the image in 4K.</p></div>${library}</div></section>
<section class="container legacy-tours"><div><p class="eyebrow"><span class="orange-dash"></span> From the original collection</p><h2>Four original bedroom tours.</h2><p>Open the original bedroom visualisations in their dedicated tour viewer.</p></div><div class="legacy-tour-links">${[1,2,3,4].map(number=>`<a href="/puruvankara/bedroom_${number}/index.html"><span>BEDROOM 0${number}</span>Open original 360° tour <span aria-hidden="true">↗</span></a>`).join('')}</div></section>
<section class="studio-footer"><div class="container"><h2>Seen something you love?</h2><p>Let’s work out how it could fit your home.</p><a class="button button-primary" href="tel:+919994958369">Call +91 99949 58369 <span aria-hidden="true">↗</span></a><a class="studio-footer-home" href="/#ourdesign">Browse the full design collection →</a><small>© <span data-year>2026</span> Alankaar Interiors</small></div></section></main></body></html>`;
  await writeFile(join(root,'studio.html'),page);return {rooms:rooms.length,designs:totalDesigns,models:models.length};
}
